name: CI & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build production assets
        run: npm run build

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}         # e.g. 52.65.158.1
          username: ${{ secrets.EC2_USER }}     # e.g. ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}       # sk
          port: 22
          script: |
            set -e
            cd /home/ec2-user/VTGMAMA
            git pull origin main
            npm ci
            npm run build
            # 平滑重载；若不存在再启动
            pm2 reload vtgmama || pm2 start npm --name vtgmama -- run start
            pm2 save
